### ISSUE TITLE
Speed comparison with calibrator

### ISSUE THREAD

**Issue by nevrome** [nevrome/currycarbon#1]
I'm trying to get at least as fast as [calibrator](https://github.com/ISAAKiel/calibrator) by @MartinHinz (discussion started in https://github.com/ISAAKiel/calibrator/issues/1)

So far it's not looking good:

```bash
$ time ./calibrator -i ../data/input_test.csv > /dev/null

real	0m0,171s
user	0m0,162s
sys	0m0,009s
```

```bash
$ time currycarbon calibrate "1000+200;2000+200;3000+200;4000+200;5000+200;6000+200;7000+200;8000+200" --densityFile /dev/null
Loading calibration curve
Calibrating
Writing density file
Done

real	0m0,675s
user	0m4,261s
sys	0m0,433s
```

But now I realised that calibrator only returns a 5-year resolution. That's a crucial difference. If I did this as well, I'm sure I could bring the runtime down a lot! 

But I don't know if I want to go there. Year-wise resolution can be useful for many applications. Maybe this should be an option to be set by the user.

**Comment by MartinHinz** [comment]
See the point. Although, it is more than the order of a magnitude. Is this really only the resolution? BtW, worth, writing an article comparing the calibration solutions in existence? Speed, and accuracy, in term of mututal agreement?

**Comment by nevrome** [comment]
Right - probably there's way more that makes currycarbon slow. 

But the yearly resolution has a number of consequences: Interpolation of intermediate calCurve values, 5 times more calls to dnorm (where the program spends 30-40% of its runtime), and also 5 times more vector-matrix multiplications (10% of the runtime).
